// AUTO-GENERATED by scripts/build-tracks.mjs — do not edit by hand.
// Source: YouTube Music playlist PLFKxbPRZ-OrE ("Diljale Aashiq").
// Change the playlist, run `npm run sync`, and this file rewrites itself.
//
// Playback runs through YouTube's official IFrame player; no audio is hosted,
// proxied or re-streamed here, so this file is metadata only.

export type RotationSlug = "judaai" | "raat" | "lofi" | "vichoda" | "sufi" | "zakhm";

export type Track = {
  /** YouTube video id — the stable key for everything, curation included */
  id: string;
  title: string;
  /** film the song is from, when the title carried it */
  film: string | null;
  /** "unplugged" / "remix" / "lofi" / … */
  badge: string | null;
  artists: string;
  /** milliseconds */
  duration: number;
  /** false when there is nothing playable; such tracks never enter a queue */
  playable: boolean;
  art: string;
  /** video ids, best first; the player falls through on error */
  yt: string[];
  rotation: RotationSlug;
  /** 1 = halka sa dard, 10 = poora tabaah */
  dard: number;
};

/** where "poori playlist" points */
export const PLAYLIST_URL = "https://music.youtube.com/playlist?list=PLFKxbPRZ-OrE";
export const PLAYLIST_NAME = "Diljale Aashiq";

export const TRACKS: Track[] = [
  {
    "id": "t4J4-K-90Ok",
    "title": "Zaroori Tha",
    "film": null,
    "badge": null,
    "artists": "The Folk & Soul Studio",
    "duration": 343000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/t4J4-K-90Ok/hqdefault.jpg",
    "yt": [
      "t4J4-K-90Ok"
    ],
    "rotation": "sufi",
    "dard": 9
  },
  {
    "id": "GtPvCa3vvxA",
    "title": "Milne Hai Mujhse Aayi",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh, Palak Muchhal",
    "duration": 221000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/GtPvCa3vvxA/hqdefault.jpg",
    "yt": [
      "GtPvCa3vvxA"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "NPC-9hYbkLE",
    "title": "Chahun Main Ya Naa",
    "film": null,
    "badge": null,
    "artists": "Palak Muchhal",
    "duration": 305000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/NPC-9hYbkLE/hqdefault.jpg",
    "yt": [
      "NPC-9hYbkLE"
    ],
    "rotation": "judaai",
    "dard": 6
  },
  {
    "id": "aVPwXQgY2QI",
    "title": "Raabta (Kehte Hain Khuda Ne)",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 290000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/aVPwXQgY2QI/hqdefault.jpg",
    "yt": [
      "aVPwXQgY2QI"
    ],
    "rotation": "judaai",
    "dard": 5
  },
  {
    "id": "xzqtxQc32Co",
    "title": "Ilahi LoFi Mix",
    "film": null,
    "badge": "lofi",
    "artists": "DJ Kedrock & SD Style",
    "duration": 164000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/xzqtxQc32Co/hqdefault.jpg",
    "yt": [
      "xzqtxQc32Co"
    ],
    "rotation": "lofi",
    "dard": 3
  },
  {
    "id": "RazuWp5kSHk",
    "title": "Kabhi Jo Badal Barse",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 143000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/RazuWp5kSHk/hqdefault.jpg",
    "yt": [
      "RazuWp5kSHk"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "Vj7jgKWnpsA",
    "title": "Do Gallan (Let's Talk)",
    "film": null,
    "badge": null,
    "artists": "Garry Sandhu",
    "duration": 252000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/Vj7jgKWnpsA/hqdefault.jpg",
    "yt": [
      "Vj7jgKWnpsA"
    ],
    "rotation": "vichoda",
    "dard": 6
  },
  {
    "id": "SbN6P-UQjcs",
    "title": "Teri Deewani",
    "film": null,
    "badge": null,
    "artists": "Kailash Kher",
    "duration": 321000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/SbN6P-UQjcs/hqdefault.jpg",
    "yt": [
      "SbN6P-UQjcs"
    ],
    "rotation": "sufi",
    "dard": 4
  },
  {
    "id": "i-EXgX279wU",
    "title": "Galliyan",
    "film": null,
    "badge": null,
    "artists": "Ankit Tiwari",
    "duration": 341000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/i-EXgX279wU/hqdefault.jpg",
    "yt": [
      "i-EXgX279wU"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "LmMzgIvIJCE",
    "title": "Ishq Mubarak",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 297000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/LmMzgIvIJCE/hqdefault.jpg",
    "yt": [
      "LmMzgIvIJCE"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "yyYpmJx8zuU",
    "title": "O Re Piya",
    "film": null,
    "badge": null,
    "artists": "The Folk & Soul Studio",
    "duration": 380000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/yyYpmJx8zuU/hqdefault.jpg",
    "yt": [
      "yyYpmJx8zuU"
    ],
    "rotation": "sufi",
    "dard": 6
  },
  {
    "id": "1b9poX5k7zo",
    "title": "Bulleya",
    "film": "Sultan",
    "badge": null,
    "artists": "Vishal - Shekhar",
    "duration": 358000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/1b9poX5k7zo/hqdefault.jpg",
    "yt": [
      "1b9poX5k7zo"
    ],
    "rotation": "sufi",
    "dard": 5
  },
  {
    "id": "xsLiUr8MOpw",
    "title": "Ishqan De Lekhe",
    "film": null,
    "badge": null,
    "artists": "S Adeeb",
    "duration": 210000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/xsLiUr8MOpw/hqdefault.jpg",
    "yt": [
      "xsLiUr8MOpw"
    ],
    "rotation": "vichoda",
    "dard": 7
  },
  {
    "id": "pqBKTLnowdM",
    "title": "Saiyyan",
    "film": null,
    "badge": null,
    "artists": "Kailasa",
    "duration": 344000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/pqBKTLnowdM/hqdefault.jpg",
    "yt": [
      "pqBKTLnowdM"
    ],
    "rotation": "sufi",
    "dard": 4
  },
  {
    "id": "_eZnQzneuKs",
    "title": "Banjaara",
    "film": null,
    "badge": null,
    "artists": "Mohammed Irfan",
    "duration": 337000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/_eZnQzneuKs/hqdefault.jpg",
    "yt": [
      "_eZnQzneuKs"
    ],
    "rotation": "raat",
    "dard": 9
  },
  {
    "id": "WqHzTIjoooQ",
    "title": "Udaarian",
    "film": null,
    "badge": null,
    "artists": "Satinder Sartaaj",
    "duration": 343000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/WqHzTIjoooQ/hqdefault.jpg",
    "yt": [
      "WqHzTIjoooQ"
    ],
    "rotation": "vichoda",
    "dard": 8
  },
  {
    "id": "DRZHVrSmcWU",
    "title": "Barbaad",
    "film": "Saiyaara",
    "badge": null,
    "artists": "Jubin Nautiyal",
    "duration": 358000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/DRZHVrSmcWU/hqdefault.jpg",
    "yt": [
      "DRZHVrSmcWU"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "uT_HXrrmHX8",
    "title": "Sitaare",
    "film": "Ikkis",
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 243000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/uT_HXrrmHX8/hqdefault.jpg",
    "yt": [
      "uT_HXrrmHX8"
    ],
    "rotation": "judaai",
    "dard": 6
  },
  {
    "id": "t6vm8h5BDxo",
    "title": "Sajjan Raazi",
    "film": null,
    "badge": null,
    "artists": "Satinder Sartaaj",
    "duration": 333000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/t6vm8h5BDxo/hqdefault.jpg",
    "yt": [
      "t6vm8h5BDxo"
    ],
    "rotation": "vichoda",
    "dard": 6
  },
  {
    "id": "yXjzqdnfkyo",
    "title": "Kite Kalli",
    "film": null,
    "badge": null,
    "artists": "Maninder Buttar",
    "duration": 210000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/yXjzqdnfkyo/hqdefault.jpg",
    "yt": [
      "yXjzqdnfkyo"
    ],
    "rotation": "vichoda",
    "dard": 5
  },
  {
    "id": "zgJPTTiCK2E",
    "title": "Piya Ghar Aavenge",
    "film": null,
    "badge": null,
    "artists": "Kailasa",
    "duration": 343000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/zgJPTTiCK2E/hqdefault.jpg",
    "yt": [
      "zgJPTTiCK2E"
    ],
    "rotation": "sufi",
    "dard": 3
  },
  {
    "id": "Gplxsk25GtY",
    "title": "Dillagi",
    "film": null,
    "badge": null,
    "artists": "The Folk & Soul Studio",
    "duration": 300000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/Gplxsk25GtY/hqdefault.jpg",
    "yt": [
      "Gplxsk25GtY"
    ],
    "rotation": "sufi",
    "dard": 6
  },
  {
    "id": "tLaJFnc93Oc",
    "title": "Tum Hi Aana",
    "film": "Marjaavaan",
    "badge": null,
    "artists": "Payal Dev",
    "duration": 250000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/tLaJFnc93Oc/hqdefault.jpg",
    "yt": [
      "tLaJFnc93Oc"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "hmsebjbRb1k",
    "title": "Uska Hi Banana",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 328000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/hmsebjbRb1k/hqdefault.jpg",
    "yt": [
      "hmsebjbRb1k"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "KKzpJ2UmCdY",
    "title": "Dost Banke",
    "film": null,
    "badge": null,
    "artists": "The Folk & Soul Studio",
    "duration": 290000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/KKzpJ2UmCdY/hqdefault.jpg",
    "yt": [
      "KKzpJ2UmCdY"
    ],
    "rotation": "zakhm",
    "dard": 5
  },
  {
    "id": "f419vqAt8PU",
    "title": "Ishq",
    "film": "Lost;Found",
    "badge": null,
    "artists": "Faheem Abdullah",
    "duration": 229000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/f419vqAt8PU/hqdefault.jpg",
    "yt": [
      "f419vqAt8PU"
    ],
    "rotation": "zakhm",
    "dard": 8
  },
  {
    "id": "o-9VdyXZKsQ",
    "title": "Tujhe Bhula Diya",
    "film": null,
    "badge": null,
    "artists": "Mohit Chauhan",
    "duration": 280000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/o-9VdyXZKsQ/hqdefault.jpg",
    "yt": [
      "o-9VdyXZKsQ"
    ],
    "rotation": "raat",
    "dard": 8
  },
  {
    "id": "ZVyA_8rd1Ko",
    "title": "Kaun Tujhe",
    "film": null,
    "badge": null,
    "artists": "Palak Muchhal",
    "duration": 242000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/ZVyA_8rd1Ko/hqdefault.jpg",
    "yt": [
      "ZVyA_8rd1Ko"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "F-6RyomnTZE",
    "title": "Dard Dilo Ke",
    "film": null,
    "badge": null,
    "artists": "Mohammed Irfan",
    "duration": 304000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/F-6RyomnTZE/hqdefault.jpg",
    "yt": [
      "F-6RyomnTZE"
    ],
    "rotation": "raat",
    "dard": 9
  },
  {
    "id": "5whLJPwIVxk",
    "title": "Jitni Dafa",
    "film": null,
    "badge": null,
    "artists": "Yasser Desai",
    "duration": 223000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/5whLJPwIVxk/hqdefault.jpg",
    "yt": [
      "5whLJPwIVxk"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "Fi3GovijpWA",
    "title": "Tere Bina",
    "film": null,
    "badge": null,
    "artists": "A. R. Rahman",
    "duration": 310000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/Fi3GovijpWA/hqdefault.jpg",
    "yt": [
      "Fi3GovijpWA"
    ],
    "rotation": "sufi",
    "dard": 5
  },
  {
    "id": "0uP0seKs5qA",
    "title": "Baaton Ko Teri",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 281000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/0uP0seKs5qA/hqdefault.jpg",
    "yt": [
      "0uP0seKs5qA"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "IgITZfS7L_8",
    "title": "Dil Ibaadat",
    "film": null,
    "badge": null,
    "artists": "Kay Kay",
    "duration": 330000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/IgITZfS7L_8/hqdefault.jpg",
    "yt": [
      "IgITZfS7L_8"
    ],
    "rotation": "judaai",
    "dard": 7
  },
  {
    "id": "iyxByIhwrC0",
    "title": "Mere Rashke Qamar",
    "film": "Baadshaho",
    "badge": null,
    "artists": "Nusrat Fateh Ali Khan",
    "duration": 221000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/iyxByIhwrC0/hqdefault.jpg",
    "yt": [
      "iyxByIhwrC0"
    ],
    "rotation": "sufi",
    "dard": 6
  },
  {
    "id": "fsiPzT50ZiM",
    "title": "Tum Hi Ho",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 262000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/fsiPzT50ZiM/hqdefault.jpg",
    "yt": [
      "fsiPzT50ZiM"
    ],
    "rotation": "judaai",
    "dard": 9
  },
  {
    "id": "q1uPPBJ2tcI",
    "title": "Phir Bhi Tumko Chaahunga",
    "film": null,
    "badge": null,
    "artists": "Mithoon",
    "duration": 352000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/q1uPPBJ2tcI/hqdefault.jpg",
    "yt": [
      "q1uPPBJ2tcI"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "7To7ajeQBE0",
    "title": "Sayar Dore",
    "film": null,
    "badge": null,
    "artists": "Zubeen Garg",
    "duration": 298000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/7To7ajeQBE0/hqdefault.jpg",
    "yt": [
      "7To7ajeQBE0"
    ],
    "rotation": "zakhm",
    "dard": 6
  },
  {
    "id": "LH9REAV5UzU",
    "title": "Maula Mere Maula",
    "film": null,
    "badge": null,
    "artists": "Roopkumar Rathod",
    "duration": 365000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/LH9REAV5UzU/hqdefault.jpg",
    "yt": [
      "LH9REAV5UzU"
    ],
    "rotation": "sufi",
    "dard": 8
  },
  {
    "id": "7BFHPc3r9QA",
    "title": "Ijazat",
    "film": null,
    "badge": null,
    "artists": "Falak Shabir",
    "duration": 248000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/7BFHPc3r9QA/hqdefault.jpg",
    "yt": [
      "7BFHPc3r9QA"
    ],
    "rotation": "zakhm",
    "dard": 8
  },
  {
    "id": "d0JpdfOLXI0",
    "title": "Pal Pal Dil Ke Paas",
    "film": "Blackmail",
    "badge": null,
    "artists": "Kishore Kumar",
    "duration": 330000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/d0JpdfOLXI0/hqdefault.jpg",
    "yt": [
      "d0JpdfOLXI0"
    ],
    "rotation": "judaai",
    "dard": 5
  },
  {
    "id": "6fXfuiJu79Y",
    "title": "Ae Dil Hai Mushkil Title Track",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 270000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/6fXfuiJu79Y/hqdefault.jpg",
    "yt": [
      "6fXfuiJu79Y"
    ],
    "rotation": "raat",
    "dard": 9
  },
  {
    "id": "6SvmykHIa4M",
    "title": "Bulleya",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 349000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/6SvmykHIa4M/hqdefault.jpg",
    "yt": [
      "6SvmykHIa4M"
    ],
    "rotation": "judaai",
    "dard": 6
  },
  {
    "id": "UyEhWtpfIFc",
    "title": "Channa Mereya",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 290000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/UyEhWtpfIFc/hqdefault.jpg",
    "yt": [
      "UyEhWtpfIFc"
    ],
    "rotation": "raat",
    "dard": 10
  },
  {
    "id": "-NjjJfmkTh8",
    "title": "The Breakup Song",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 253000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/-NjjJfmkTh8/hqdefault.jpg",
    "yt": [
      "-NjjJfmkTh8"
    ],
    "rotation": "judaai",
    "dard": 3
  },
  {
    "id": "BaX-TUvuCNQ",
    "title": "Cutiepie",
    "film": null,
    "badge": null,
    "artists": "Pritam",
    "duration": 232000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/BaX-TUvuCNQ/hqdefault.jpg",
    "yt": [
      "BaX-TUvuCNQ"
    ],
    "rotation": "judaai",
    "dard": 2
  },
  {
    "id": "IkChiSZtrRQ",
    "title": "Alizeh",
    "film": null,
    "badge": null,
    "artists": "Arijit Singh",
    "duration": 283000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/IkChiSZtrRQ/hqdefault.jpg",
    "yt": [
      "IkChiSZtrRQ"
    ],
    "rotation": "judaai",
    "dard": 6
  },
  {
    "id": "zV7pfxeh5dY",
    "title": "Such Keh Raha Hai",
    "film": null,
    "badge": null,
    "artists": "Kay Kay",
    "duration": 329000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/zV7pfxeh5dY/hqdefault.jpg",
    "yt": [
      "zV7pfxeh5dY"
    ],
    "rotation": "raat",
    "dard": 8
  },
  {
    "id": "WT1qB8SKi2s",
    "title": "Teri Yaad…Yaad",
    "film": null,
    "badge": null,
    "artists": "Kay Kay",
    "duration": 297000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/WT1qB8SKi2s/hqdefault.jpg",
    "yt": [
      "WT1qB8SKi2s"
    ],
    "rotation": "raat",
    "dard": 8
  },
  {
    "id": "zRKvLzLVIKQ",
    "title": "Tera Zikr",
    "film": null,
    "badge": null,
    "artists": "Darshan Raval",
    "duration": 209000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/zRKvLzLVIKQ/hqdefault.jpg",
    "yt": [
      "zRKvLzLVIKQ"
    ],
    "rotation": "zakhm",
    "dard": 7
  },
  {
    "id": "Zk_9vHhOcNg",
    "title": "Khamoshiyan",
    "film": null,
    "badge": null,
    "artists": "Jeet Gannguli",
    "duration": 336000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/Zk_9vHhOcNg/hqdefault.jpg",
    "yt": [
      "Zk_9vHhOcNg"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "pI2vTj8Au7Y",
    "title": "Tu Har Lamha",
    "film": null,
    "badge": null,
    "artists": "Bobby-Imran",
    "duration": 273000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/pI2vTj8Au7Y/hqdefault.jpg",
    "yt": [
      "pI2vTj8Au7Y"
    ],
    "rotation": "judaai",
    "dard": 8
  },
  {
    "id": "iKopExw_3Zg",
    "title": "Baatein Ye Kabhi Na (Male)",
    "film": null,
    "badge": "male",
    "artists": "Jeet Gannguli",
    "duration": 290000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/iKopExw_3Zg/hqdefault.jpg",
    "yt": [
      "iKopExw_3Zg"
    ],
    "rotation": "raat",
    "dard": 8
  },
  {
    "id": "F3KaU2uchTY",
    "title": "Kya Khoya",
    "film": null,
    "badge": null,
    "artists": "Naved Zafar",
    "duration": 329000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/F3KaU2uchTY/hqdefault.jpg",
    "yt": [
      "F3KaU2uchTY"
    ],
    "rotation": "zakhm",
    "dard": 7
  },
  {
    "id": "JQgR9vZzeIg",
    "title": "Bheegh Loon (Female)",
    "film": null,
    "badge": "female",
    "artists": "Ankit Tiwari",
    "duration": 248000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/JQgR9vZzeIg/hqdefault.jpg",
    "yt": [
      "JQgR9vZzeIg"
    ],
    "rotation": "judaai",
    "dard": 5
  },
  {
    "id": "MsVUBMmkGJ4",
    "title": "Subhan Allah",
    "film": null,
    "badge": null,
    "artists": "Bobby-Imran",
    "duration": 272000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/MsVUBMmkGJ4/hqdefault.jpg",
    "yt": [
      "MsVUBMmkGJ4"
    ],
    "rotation": "sufi",
    "dard": 4
  },
  {
    "id": "8Sy2VwQlMyo",
    "title": "Bheegh Loon (Male)",
    "film": null,
    "badge": "male",
    "artists": "Ankit Tiwari",
    "duration": 248000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/8Sy2VwQlMyo/hqdefault.jpg",
    "yt": [
      "8Sy2VwQlMyo"
    ],
    "rotation": "judaai",
    "dard": 5
  },
  {
    "id": "oJzVtFX7OjY",
    "title": "Baatein Ye Kabhi Na (Female)",
    "film": null,
    "badge": "female",
    "artists": "Jeet Gannguli",
    "duration": 290000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/oJzVtFX7OjY/hqdefault.jpg",
    "yt": [
      "oJzVtFX7OjY"
    ],
    "rotation": "raat",
    "dard": 8
  },
  {
    "id": "qbFpb4v68i4",
    "title": "Khamoshiyan (Unplugged)",
    "film": null,
    "badge": "unplugged",
    "artists": "Jeet Gannguli",
    "duration": 151000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/qbFpb4v68i4/hqdefault.jpg",
    "yt": [
      "qbFpb4v68i4"
    ],
    "rotation": "lofi",
    "dard": 6
  },
  {
    "id": "4oF7eCIH58U",
    "title": "Tu Har Lamha (Remix by DJ Angel)",
    "film": null,
    "badge": "remix",
    "artists": "Bobby-Imran",
    "duration": 258000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/4oF7eCIH58U/hqdefault.jpg",
    "yt": [
      "4oF7eCIH58U"
    ],
    "rotation": "lofi",
    "dard": 6
  },
  {
    "id": "p7yy0Ix9Hrc",
    "title": "Bheegh Loon (Female - Remix by DJ Angel)",
    "film": null,
    "badge": "remix",
    "artists": "Ankit Tiwari",
    "duration": 196000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/p7yy0Ix9Hrc/hqdefault.jpg",
    "yt": [
      "p7yy0Ix9Hrc"
    ],
    "rotation": "lofi",
    "dard": 5
  },
  {
    "id": "jNDot_dDokk",
    "title": "Jaan",
    "film": null,
    "badge": null,
    "artists": "Happy Raikoti",
    "duration": 228000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/jNDot_dDokk/hqdefault.jpg",
    "yt": [
      "jNDot_dDokk"
    ],
    "rotation": "vichoda",
    "dard": 7
  },
  {
    "id": "3X1tNeiz-jI",
    "title": "Kade Ta Tu Avenga",
    "film": null,
    "badge": null,
    "artists": "Runbir",
    "duration": 276000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/3X1tNeiz-jI/hqdefault.jpg",
    "yt": [
      "3X1tNeiz-jI"
    ],
    "rotation": "vichoda",
    "dard": 8
  },
  {
    "id": "IOxTTrsCw_E",
    "title": "Jannat",
    "film": null,
    "badge": null,
    "artists": "B Praak",
    "duration": 206000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/IOxTTrsCw_E/hqdefault.jpg",
    "yt": [
      "IOxTTrsCw_E"
    ],
    "rotation": "vichoda",
    "dard": 8
  },
  {
    "id": "dO8SmS8q9HU",
    "title": "Paani",
    "film": null,
    "badge": null,
    "artists": "Yuvraaj Hans",
    "duration": 186000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/dO8SmS8q9HU/hqdefault.jpg",
    "yt": [
      "dO8SmS8q9HU"
    ],
    "rotation": "vichoda",
    "dard": 7
  },
  {
    "id": "Ih24MPuvdhs",
    "title": "Mann Bharrya",
    "film": null,
    "badge": null,
    "artists": "B Praak",
    "duration": 277000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/Ih24MPuvdhs/hqdefault.jpg",
    "yt": [
      "Ih24MPuvdhs"
    ],
    "rotation": "vichoda",
    "dard": 9
  },
  {
    "id": "EA3wqy77yDg",
    "title": "Taara",
    "film": null,
    "badge": null,
    "artists": "Ammy Virk",
    "duration": 279000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/EA3wqy77yDg/hqdefault.jpg",
    "yt": [
      "EA3wqy77yDg"
    ],
    "rotation": "vichoda",
    "dard": 8
  },
  {
    "id": "C1CEgV155J8",
    "title": "Haaye Ve",
    "film": null,
    "badge": null,
    "artists": "Ammy Virk",
    "duration": 216000,
    "playable": true,
    "art": "https://i.ytimg.com/vi/C1CEgV155J8/hqdefault.jpg",
    "yt": [
      "C1CEgV155J8"
    ],
    "rotation": "vichoda",
    "dard": 8
  }
];
